const actionTypes = {
  LOGIN_ISLOADING: 'LOGIN_ISLOADING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  REGISTER_ISLOADING: 'REGISTER_ISLOADING',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
};

export default actionTypes;
