const actionTypes = {
  FETCH_FOOD_FAILURE: 'FETCH_FOOD_FAILURE',
  FETCH_FOOD_LOADING: 'FETCH_FOOD_LOADING',
  FETCH_FOOD_SUCCESS: 'FETCH_FOOD_SUCCESS',
  CHANGE_FOOD_FETCH_STATE: 'CHANGE_FOOD_FETCH_STATE',
  ORDER_ISLOADING: 'ORDER_ISLOADING',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  ORDER_FAILURE: 'ORDER_FAILURE'
};

export default actionTypes;
